Repository Blu-e-project/Blu-e-backend, pull requests merged in 2023-01, with the labels that each got.

#1 [ADD] 프로젝트 초기 설정
  .gitignore
  config/baseResponseStatus.js
  config/database.js
  config/express.js
  config/jwtMiddleware.js
  config/response.js
  config/winston.js
  index.js
  package.json
  src/app/User/userRoute.js
Labels: davin

#4 기본 회원가입 기능 구현
  .gitignore
  config/baseResponseStatus.js
  package.json
  src/app/User/userController.js
  src/app/User/userDao.js
  src/app/User/userProvider.js
  src/app/User/userRoute.js
  src/app/User/userService.js
Labels: I'm trying 💪, question ❓, seohee 🤪

#7 [MOD] userDao, baseResponseStatus 수정
  config/baseResponseStatus.js
  src/app/User/userDao.js
Labels: seohee 🤪, done ✔

#9 [MOD] userController.js, userRoute.js 코드 수정
  src/app/User/userController.js
  src/app/User/userRoute.js
Labels: done ✔, jonghan

#10 [FEAT] Question 수정 기능 구현
  src/app/User/userController.js
  src/app/User/userDao.js
  src/app/User/userRoute.js
  src/app/User/userService.js
Labels: done ✔, jonghan

#11 [FEAT] 궁금한 문제 생성 API
  config/baseResponseStatus.js
  config/express.js
  src/app/Problem/problemController.js
  src/app/Problem/problemDao.js
  src/app/Problem/problemProvider.js
  src/app/Problem/problemRoute.js
  src/app/Problem/problemService.js
Labels: davin

#12 [FEAT] 문제 전체 조회, 부분 조회 기능 구현
  src/app/Problem/problemController.js
  src/app/Problem/problemDao.js
  src/app/Problem/problemProvider.js
  src/app/Problem/problemRoute.js
Labels: davin

#13 [MOVE] question관련 API들 src/app/Question으로 이동
  src/app/Question/questionController.js
  src/app/Question/questionDao.js
  src/app/Question/questionProvider.js
  src/app/Question/questionRoute.js
  src/app/Question/questionService.js
  src/app/User/userController.js
  src/app/User/userDao.js
  src/app/User/userProvider.js
  src/app/User/userRoute.js
  src/app/User/userService.js
Labels: done ✔, jonghan

#15 [FEAT] JWT 미들웨어(인증) 구현
  config/jwtMiddleware.js
Labels: done ✔, davin

#16 [MOD] userService.js 코드 수정
  src/app/User/userService.js
Labels: seohee 🤪, done ✔

#19 [MOD] userService.js 파일 수정
  src/app/User/userService.js
Labels: seohee 🤪

#20 [MOD] 문제 생성, 조회 기능내에 JWT 인증 미들웨어 추가, userService.js 수정
  .gitignore
  config/baseResponseStatus.js
  src/app/Problem/problemController.js
  src/app/Problem/problemDao.js
  src/app/Problem/problemRoute.js
  src/app/Problem/problemService.js
  src/app/User/userService.js
Labels: done ✔, davin

#21 [MOD] userService.js 파일 수정
  src/app/User/userService.js
Labels: seohee 🤪

#22 [FEAT] 궁금한 문제 삭제 기능 구현
  config/baseResponseStatus.js
  src/app/Problem/problemController.js
  src/app/Problem/problemDao.js
  src/app/Problem/problemRoute.js
  src/app/Problem/problemService.js
Labels: seohyeon

#23 [FEAT] 멘토 전체 조회, 멘티 전체 조회(최신순) 기능 구현
  src/app/User/userController.js
  src/app/User/userDao.js
  src/app/User/userProvider.js
  src/app/User/userRoute.js
Labels: done ✔, davin

#26 [FEAT] 멘토, 멘티 전체조회 및 프로필 조회 기능 구현
  config/baseResponseStatus.js
  src/app/Problem/problemDao.js
  src/app/User/userDao.js
Labels: done ✔, davin

#27 [MOD] questionDao.js에 selectQuestion 쿼리문 수정
  src/app/Question/questionDao.js
Labels: done ✔, jonghan

#28 [FEAT] Question 삭제 기능 구현
  src/app/Question/questionController.js
  src/app/Question/questionDao.js
  src/app/Question/questionRoute.js
  src/app/Question/questionService.js
Labels: done ✔, jonghan

#29 [FEAT] 멘토 구인글, 멘티 구인글 전체 조회 기능 구현
  config/express.js
  src/app/Mentoring/mentoringController.js
  src/app/Mentoring/mentoringDao.js
  src/app/Mentoring/mentoringProvider.js
  src/app/Mentoring/mentoringRoute.js
  src/app/Mentoring/mentoringService.js
Labels: done ✔, davin

#30 [FEAT] 메인화면 멘토, 멘티 부분 조회 기능 구현
  src/app/Mentoring/mentoringController.js
  src/app/Mentoring/mentoringDao.js
  src/app/Mentoring/mentoringProvider.js
  src/app/Mentoring/mentoringRoute.js
  src/app/User/userController.js
  src/app/User/userDao.js
  src/app/User/userProvider.js
  src/app/User/userRoute.js
Labels: done ✔, davin

#32 [ADD] 회원가입 SQL, response 코드 추가
  config/baseResponseStatus.js
  src/app/User/userController.js
  src/app/User/userDao.js
  src/app/User/userRoute.js
  src/app/User/userService.js
Labels: seohee 🤪, done ✔

#35 [FEAT] problemController.js 수정
  config/baseResponseStatus.js
  src/app/Problem/problemController.js
Labels: done ✔, davin

#36 [MOD] baseResponse에 Question관련 메시지 추가, question 파일들 일부 수정
  config/baseResponseStatus.js
  config/database.js
  src/app/Question/questionController.js
  src/app/Question/questionDao.js
  src/app/Question/questionRoute.js
Labels: done ✔, jonghan

#38 [FEAT] 휴대폰 인증 구현
  .gitignore
  config/baseResponseStatus.js
  config/database.js
  config/secret_sms.js
  src/app/User/userController.js
  src/app/User/userRoute.js
Labels: seohee 🤪, done ✔
