Repository Blu-e-project/Blu-e-backend, pull requests merged in 2023-02, with the labels that each got.

#40 [ADD] Report 폴더 생성
  src/app/Report/reportController.js
  src/app/Report/reportDao.js
  src/app/Report/reportProvider.js
  src/app/Report/reportRoute.js
  src/app/Report/reportService.js
Labels: done ✔, jonghan

#41 [MOD] baseResponseStauts.js, questionController.js 수정
  config/baseResponseStatus.js
  config/express.js
  src/app/Question/questionController.js
Labels: done ✔, jonghan

#44 [ADD] Editing 폴더 생성
  config/database.js
  package.json
  src/app/Editing/editingController.js
  src/app/Editing/editingDao.js
  src/app/Editing/editingProvider.js
  src/app/Editing/editingRoute.js
  src/app/Editing/editingService.js
  src/app/User/userController.js
Labels: done ✔, jonghan

#45 [MOD] 멘토, 멘티 구인글 부분 조회 기능 수정
  src/app/Mentoring/mentoringController.js
  src/app/Mentoring/mentoringDao.js
  src/app/Mentoring/mentoringRoute.js
Labels: done ✔, davin

#46 [MOD] questionController.js, quesitonDao.js, questionProvider.js, eustionRoute.js, questionService.js 파일 필요없는 API 삭제
  config/baseResponseStatus.js
  config/express.js
  src/app/Editing/editingController.js
  src/app/Editing/editingDao.js
  src/app/Editing/editingRoute.js
  src/app/Editing/editingService.js
  src/app/Question/questionController.js
  src/app/Question/questionDao.js
  src/app/Question/questionProvider.js
  src/app/Question/questionRoute.js
  src/app/Question/questionService.js
Labels: done ✔, jonghan

#47 [MERGE] baseResponseStatus.js 충돌 해결
  config/baseResponseStatus.js
  src/app/Mentoring/mentoringController.js
  src/app/Mentoring/mentoringDao.js
  src/app/Mentoring/mentoringRoute.js
  src/app/Mentoring/mentoringService.js
  src/app/Problem/problemController.js
Labels: done ✔, davin

#49 [FEAT] 특정 멘토, 멘티 구인글 조회 기능 구현
  src/app/Mentoring/mentoringController.js
  src/app/Mentoring/mentoringDao.js
  src/app/Mentoring/mentoringProvider.js
  src/app/Mentoring/mentoringRoute.js
Labels: done ✔, davin

#50 [FEAT] 멘토 구인글 댓글 CRUD 기능 구현
  config/baseResponseStatus.js
  src/app/Mentoring/mentoringController.js
  src/app/Mentoring/mentoringDao.js
  src/app/Mentoring/mentoringProvider.js
  src/app/Mentoring/mentoringRoute.js
  src/app/Mentoring/mentoringService.js
Labels: seohee 🤪, done ✔

#52 [MOD] baseResponseStatus.js 수정
  config/baseResponseStatus.js
Labels: done ✔, davin

#53 [MOD] 특정 구인글 조회 시 조회수 증가 기능 추가 구현
  src/app/Mentoring/mentoringDao.js
  src/app/Mentoring/mentoringProvider.js
Labels: done ✔, davin

#54 [FEAT] 회원 정보 수정에서 닉네임 중복 확인 기능 구현, 신고 누적 기능 구현
  config/baseResponseStatus.js
  src/app/Editing/editingDao.js
  src/app/Editing/editingProvider.js
  src/app/Editing/editingService.js
  src/app/Report/reportController.js
  src/app/Report/reportDao.js
  src/app/Report/reportService.js
Labels: jonghan

#55 [FEAT] 비밀번호 수정 기능 구현
  config/baseResponseStatus.js
  src/app/Editing/editingController.js
  src/app/Editing/editingDao.js
  src/app/Editing/editingRoute.js
  src/app/Editing/editingService.js
  src/app/Question/questionController.js
  src/app/Report/reportController.js
Labels: done ✔, jonghan

#56 [FEAT] 신고누적값 3회 이상시 Status값 0으로 변경 기능
  src/app/Report/reportDao.js
  src/app/Report/reportService.js
Labels: jonghan

#57 [MOD] Report, Question, Editing 폴더의 파일들 부분수정
  config/baseResponseStatus.js
  src/app/Editing/editingController.js
  src/app/Editing/editingRoute.js
  src/app/Question/questionController.js
  src/app/Question/questionRoute.js
  src/app/Report/reportController.js
  src/app/Report/reportRoute.js
  src/app/Report/reportService.js
Labels: jonghan

#59 [CHORE] reviewRoute 주석처리 수정
  src/app/Review/reviewRoute.js
Labels: done ✔, seohyeon

#60 [MOD] 구인글 관련 사용자 인증 과정 추가 구현
  config/baseResponseStatus.js
  src/app/Mentoring/mentoringController.js
  src/app/Mentoring/mentoringDao.js
  src/app/Mentoring/mentoringProvider.js
  src/app/Mentoring/mentoringService.js
Labels: done ✔, davin

#62 [FEAT] 아이디 찾기, 비밀번호 재설정 기능 구현
  src/app/User/userController.js
  src/app/User/userDao.js
  src/app/User/userProvider.js
  src/app/User/userRoute.js
  src/app/User/userService.js
Labels: I'm trying 💪, seohee 🤪

#63 [FEAT] 내가 답변한 문제 조회 기능 구현
  src/app/Problem/problemController.js
  src/app/Problem/problemDao.js
  src/app/Problem/problemProvider.js
  src/app/Problem/problemRoute.js
Labels: done ✔, seohyeon

#65 [FEAT] 멘토, 멘티 구인글 수정 기능 구현
  src/app/Mentoring/mentoringController.js
  src/app/Mentoring/mentoringDao.js
  src/app/Mentoring/mentoringRoute.js
  src/app/Mentoring/mentoringService.js
Labels: done ✔, davin

#66 [FEAT] 멘티 구인글 댓글 CR 기능 구현
  config/baseResponseStatus.js
  src/app/Mentoring/mentoringController.js
  src/app/Mentoring/mentoringDao.js
  src/app/Mentoring/mentoringProvider.js
  src/app/Mentoring/mentoringRoute.js
  src/app/Mentoring/mentoringService.js
Labels: seohee 🤪, done ✔

#67 [FEAT] 멘토링 댓글 CRUD 기능 구현
  config/baseResponseStatus.js
  src/app/Mentoring/mentoringController.js
  src/app/Mentoring/mentoringDao.js
  src/app/Mentoring/mentoringProvider.js
  src/app/Mentoring/mentoringRoute.js
  src/app/Mentoring/mentoringService.js
  src/app/User/userService.js
Labels: seohee 🤪, done ✔

#68 [ADD] baseResponseStatues.js 추가
  config/baseResponseStatus.js
  src/app/Editing/editingController.js
  src/app/Question/questionController.js
Labels: done ✔, jonghan

#70 [MOD] 신고 시에 아이디 선택에서 닉네임 선택으로 변경
  src/app/Report/reportController.js
  src/app/Report/reportDao.js
  src/app/Report/reportService.js
Labels: done ✔, jonghan

#71 [FEAT] 매칭 기능 구현
  config/baseResponseStatus.js
  src/app/Mentoring/mentoringController.js
  src/app/Mentoring/mentoringDao.js
  src/app/Mentoring/mentoringProvider.js
  src/app/Mentoring/mentoringRoute.js
  src/app/Mentoring/mentoringService.js
Labels: seohee 🤪, done ✔

#72 [MOD] problemDao 등록일 조회 가능하게 수정
  src/app/Problem/problemDao.js
  src/app/Problem/problemRoute.js
Labels: done ✔, seohyeon

#73 [FEAT] 신고하려는 유저와 매칭 되어 있는 지 확인 기능 구현
  config/baseResponseStatus.js
  src/app/Report/reportDao.js
  src/app/Report/reportProvider.js
  src/app/Report/reportService.js
Labels: done ✔, jonghan

#75 [FEAT] Question의 답변이 없을 때, [답변 대기 중] 문구 출력 기능 추가
  src/app/Question/questionDao.js
  src/app/Question/questionService.js
Labels: done ✔, jonghan

#76 [ADD] 매칭 수락 버튼 userId 확인 추가
  config/baseResponseStatus.js
  src/app/Mentoring/mentoringController.js
  src/app/Mentoring/mentoringDao.js
  src/app/Mentoring/mentoringProvider.js
Labels: I'm trying 💪, done ✔

#78 [FEAT] 내가 쓴 구인글 조회 기능 구현
  config/express.js
  src/app/MyPage/myPageController.js
  src/app/MyPage/myPageDao.js
  src/app/MyPage/myPageProvider.js
  src/app/MyPage/myPageRoute.js
  src/app/MyPage/myPageService.js
Labels: seohyeon

#79 [FEAT] 내가 댓글 쓴 구인글 조회 기능 구현
  src/app/MyPage/myPageController.js
  src/app/MyPage/myPageDao.js
  src/app/MyPage/myPageProvider.js
  src/app/MyPage/myPageRoute.js
Labels: seohyeon

#80 [FEAT] 멘토링 내역 조회
  src/app/Mentoring/mentoringController.js
  src/app/Mentoring/mentoringDao.js
  src/app/Mentoring/mentoringProvider.js
  src/app/Mentoring/mentoringRoute.js
Labels: seohee 🤪, done ✔

#81 [MOD] myPageDao 수정
  src/app/MyPage/myPageDao.js
Labels: done ✔, seohyeon

#82 [MOD] reportDao.js, reportService.js 일부 수정
  src/app/Report/reportDao.js
  src/app/Report/reportService.js
Labels: done ✔, jonghan

#83 [FEAT] 피신고자의 status값 확인 기능 구현
  config/baseResponseStatus.js
  src/app/Report/reportDao.js
  src/app/Report/reportProvider.js
  src/app/Report/reportService.js
Labels: done ✔, jonghan

#84 [MOD] 리뷰 작성 관련 기능 추가 구현
  src/app/Review/reviewController.js
  src/app/Review/reviewDao.js
  src/app/Review/reviewProvider.js
  src/app/Review/reviewRoute.js
  src/app/Review/reviewService.js
Labels: done ✔, seohyeon

#85 [MOD] editingController.js, questionService.js 파일 일부 수정
  src/app/Editing/editingController.js
  src/app/Question/questionService.js
Labels: done ✔, jonghan

#87 [MOD] 멘토링 내역 조회 및 멘토링 댓글 조회 코드 수정
  src/app/Mentoring/mentoringController.js
  src/app/Mentoring/mentoringDao.js
  src/app/Mentoring/mentoringProvider.js
  src/app/Mentoring/mentoringRoute.js
  src/app/MyPage/myPageController.js
  src/app/MyPage/myPageDao.js
  src/app/MyPage/myPageProvider.js
  src/app/MyPage/myPageRoute.js
Labels: I'm trying 💪, done ✔

#88 [MOD] 내가 쓴 리뷰 쿼리문 수정
  src/app/Review/reviewDao.js
Labels: done ✔, seohyeon

#89 [MOD] 내가 쓴 리뷰 조회 쿼리 수정
  src/app/Review/reviewDao.js
Labels: done ✔, seohyeon

#90 [MOD] 내가 쓴 구인글 조회, 내가 댓글 쓴 구인글 조회 관련 코드 수정
  src/app/MyPage/myPageController.js
  src/app/MyPage/myPageDao.js
  src/app/MyPage/myPageProvider.js
Labels: done ✔, seohyeon

#91 [MOD] baseResponseStatus.js 수정
  config/baseResponseStatus.js
Labels: done ✔, seohyeon

#92 [MOD] express.js 파일 수정
  config/express.js
Labels: done ✔, jonghan

#93 [MOD] problemDao 수정
  src/app/Problem/problemDao.js
Labels: done ✔, seohyeon

#94 [MOD] mentoringDao.js 수정
  src/app/Mentoring/mentoringDao.js
Labels: done ✔, davin

#96 [MOD] mentoringDao.js 수정
  src/app/Mentoring/mentoringDao.js
Labels: done ✔, davin

#97 [MOD] mentoringDao.js 수정
  src/app/Mentoring/mentoringDao.js
Labels: done ✔, davin

#98 [MOD] mentoringDao pickcomment 테이블명 수정
  src/app/Mentoring/mentoringDao.js
Labels: seohee 🤪, done ✔

#101 [MOD] reviewController 수정
  src/app/Review/reviewController.js
Labels: done ✔, seohyeon

#102 Davin
  src/app/Mentoring/mentoringDao.js
  src/app/Mentoring/mentoringProvider.js
  src/app/Mentoring/mentoringService.js
Labels: done ✔, davin

#106 [FEAT] 문제 5개 부분 조회 기능 추가
  src/app/Problem/problemController.js
  src/app/Problem/problemDao.js
  src/app/Problem/problemProvider.js
  src/app/Problem/problemRoute.js
Labels: done ✔, davin

#107 [MOD] userController.js 수정
  src/app/User/userController.js
Labels: seohee 🤪, done ✔

#109 [MOD] 문제 부분 조회(최신 5개) 기능 수정
  src/app/Problem/problemController.js
  src/app/Problem/problemDao.js
  src/app/Problem/problemProvider.js
  src/app/Problem/problemRoute.js
Labels: done ✔, davin

#110 [MOD] 멘토 구인글 삭제 기능 수정
  src/app/Mentoring/mentoringDao.js
  src/app/Mentoring/mentoringService.js
Labels: done ✔, davin

#111 [MOD] mentoringDao.js 수정
  src/app/Mentoring/mentoringDao.js
Labels: done ✔, davin

#112 [MOD] 구인글 삭제 관련 수정
  config/baseResponseStatus.js
  src/app/Mentoring/mentoringService.js
Labels: done ✔, davin

#113 [MOD] mentoring 관련 수정
  src/app/Mentoring/mentoringDao.js
  src/app/Mentoring/mentoringService.js
Labels: done ✔, davin

#114 [MOD] mentoring 관련 수정
  src/app/Mentoring/mentoringDao.js
  src/app/Mentoring/mentoringProvider.js
Labels: done ✔, davin

#115 [MOD] mentoring 관련 수정
  src/app/Mentoring/mentoringProvider.js
  src/app/Mentoring/mentoringService.js
Labels: done ✔, davin

#116 [MOD] mentoring 관련 수정
  src/app/Mentoring/mentoringService.js
Labels: done ✔, davin

#117 [MOD] mentoring 관련 수정
  src/app/Mentoring/mentoringService.js
Labels: done ✔, davin

#119 [MOD] 매칭체크 수정
  src/app/Mentoring/mentoringService.js
Labels: done ✔, seohyeon

#120 [MOD] mentoringDao 수정
  src/app/Mentoring/mentoringDao.js
Labels: done ✔, seohyeon

#121 [MOD] questionDao.js 수정
  config/database.js
  src/app/Question/questionDao.js
Labels: done ✔, jonghan

#122 [MOD] problemDao 수정
  src/app/Problem/problemDao.js
Labels: done ✔, seohyeon

#123 [MOD] 멘토링 구인글 댓글 조회 코드 수정
  src/app/Mentoring/mentoringController.js
  src/app/Mentoring/mentoringDao.js
  src/app/Mentoring/mentoringProvider.js
Labels: seohee 🤪, done ✔

#125 [CHORE] SELECT userId, pickId, role 칼럼 추가
  src/app/Mentoring/mentoringDao.js
  src/app/MyPage/myPageDao.js
  src/app/User/userDao.js
Labels: seohee 🤪, done ✔

#126 [MOD] 답변조회, 내가 답변한 문제 조회 userId 추가
  src/app/Problem/problemDao.js
Labels: done ✔, seohyeon

#130 [MOD] 인증번호 date 값 받아오는 코드 수정
  src/app/User/userController.js
Labels: I'm trying 💪, seohee 🤪

#131 [CHORE] userRoute.js 수정
  src/app/User/userRoute.js
Labels: seohee 🤪, done ✔

#132 [CHORE] baseResponseStatus.js 코드 추가
  config/baseResponseStatus.js
  src/app/User/userController.js
Labels: seohee 🤪, done ✔

#135 [CHORE] userController.js res 부분 수정
  src/app/User/userController.js
Labels: seohee 🤪, done ✔

#136 [FEAT] 이미지 수정 기능 추가
  src/app/Editing/editingController.js
  src/app/Editing/editingDao.js
  src/app/Editing/editingRoute.js
  src/app/Editing/editingService.js
Labels: done ✔, jonghan

#137 [CHORE] 회원가입 널값 확인 추가
  src/app/User/userController.js
Labels: seohee 🤪, done ✔

#138 [CHORE] mentoringController 수정
  src/app/Mentoring/mentoringController.js
Labels: done ✔, seohyeon

#139 [CHORE] mentoringController 수정
  src/app/Mentoring/mentoringController.js
Labels: done ✔, seohyeon

#141 [CHORE] mentoringDao.js 코드 수정
  src/app/Mentoring/mentoringDao.js
Labels: seohee 🤪, done ✔

#145 [MOD] 매칭된 구인글 댓글 조회 불가로 코드 수정
  src/app/Mentoring/mentoringController.js
Labels: seohee 🤪, done ✔

#146 [MOD] 매칭 테이블 관련 신고, 멘토링 Dao 수정
  src/app/Mentoring/mentoringController.js
  src/app/Mentoring/mentoringDao.js
  src/app/Mentoring/mentoringService.js
  src/app/Report/reportDao.js
Labels: seohee 🤪, done ✔

#147 [MOD] reviewDao.js 리뷰 조회 수정
  src/app/Review/reviewDao.js
Labels: seohee 🤪, done ✔

#148 [MOD] reviewDao 수정
  src/app/Review/reviewDao.js
Labels: done ✔, seohyeon

#149 [MOC] maPageDao 수정
  src/app/MyPage/myPageDao.js
Labels: done ✔, seohyeon

#150 [MOD] myPageDao 수정
  src/app/MyPage/myPageDao.js
Labels: done ✔, seohyeon

#151 [MOD] reviewDao 수정
  src/app/Review/reviewDao.js
Labels: done ✔, seohyeon

#152 [MOD] myPageDao 수정
  src/app/MyPage/myPageDao.js
Labels: done ✔, seohyeon

#153 [MOD] myPageDao, reviewDao 수정
  src/app/MyPage/myPageDao.js
  src/app/Review/reviewDao.js
Labels: done ✔, seohyeon

#154 [MOD] myPageDao 수정
  src/app/MyPage/myPageDao.js
Labels: done ✔, seohyeon

#155 [MOD] myPageDao 멘토링내역조회 수정
  src/app/MyPage/myPageDao.js
Labels: done ✔, seohyeon
